// FOUNDIT_FE/src/app/auth/sign-up/page.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { useAuth } from "@/components/providers/auth-provider";
import { toErrorMessage } from "@/lib/api";
import type { AppRole } from "@/types/auth";

const roles: Array<Exclude<AppRole, "ADMIN">> = ["CLIENT", "FREELANCER"];

export default function SignUpPage() {
  const router = useRouter();
  const { continueWithGoogle, signUp } = useAuth();
  const [form, setForm] = useState({
    username: "",
    email: "",
    password: "",
    role: "CLIENT" as Exclude<AppRole, "ADMIN">,
  });
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const updateField = (key: keyof typeof form, value: string) => {
    setForm((current) => ({
      ...current,
      [key]: value,
    }));
  };

  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError(null);
    setSuccess(null);

    startTransition(() => {
      void (async () => {
        try {
          await signUp(form);
          setSuccess("Account created. You can sign in with the new credentials now.");
          router.push("/auth/sign-in");
        } catch (submitError) {
          setError(toErrorMessage(submitError));
        }
      })();
    });
  };

  return (
    <section className="min-h-screen bg-[#f8f8f8] px-6 py-8 md:px-10 lg:px-16">
      <div className="mx-auto w-full">
        <div className="mb-3 flex justify-center">
          <div className="flex h-16 w-32 items-center">
            <Image
              alt="FOUNDIT"
              className="h-full w-full object-contain"
              height={64}
              priority
              src="/assets/images/logo.png"
              width={128}
            />
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1.08fr_0.92fr]">
          <div className="flex items-start justify-center px-2 pt-8 md:px-6 lg:px-4 xl:px-8">
            <div className="w-full max-w-2xl">
              <h1 className="text-[42px] font-bold leading-tight text-[#1b1b1b]">
                Create an account
              </h1>
              <p className="mt-2 text-[18px] text-[#7b7b7b]">Sign Up With FoundIT</p>

              <div className="mt-8 space-y-3">
                <button
                  className="flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-[#e3e3e3] bg-white text-[14px] font-medium text-[#222] transition hover:bg-gray-50"
                  onClick={continueWithGoogle}
                  type="button"
                >
                  <span className="inline-flex h-5 w-5 items-center justify-center rounded-full border border-gray-300 text-[11px] font-bold text-[#4285F4]">
                    G
                  </span>
                  <span>Continue with Google</span>
                </button>
              </div>

              <div className="my-6 flex items-center gap-4">
                <div className="h-px flex-1 bg-[#e5e5e5]" />
                <span className="text-[13px] text-[#8a8a8a]">or use email</span>
                <div className="h-px flex-1 bg-[#e5e5e5]" />
              </div>

              <form className="space-y-4" onSubmit={onSubmit}>
                {error ? (
                  <div className="rounded-xl border border-[#fecaca] bg-[#fef2f2] px-4 py-3 text-[14px] text-[#991b1b]">
                    {error}
                  </div>
                ) : null}

                {success ? (
                  <div className="rounded-xl border border-[#bbf7d0] bg-[#f0fdf4] px-4 py-3 text-[14px] text-[#166534]">
                    {success}
                  </div>
                ) : null}

                <div>
                  <label className="mb-2 block text-[14px] font-medium text-[#6f6f6f]" htmlFor="fullName">
                    Full name
                  </label>
                  <input
                    className="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
                    id="fullName"
                    onChange={(event) => updateField("username", event.target.value)}
                    placeholder="Your name"
                    required
                    type="text"
                    value={form.username}
                  />
                </div>

                <div>
                  <label className="mb-2 block text-[14px] font-medium text-[#6f6f6f]" htmlFor="email">
                    Email
                  </label>
                  <input
                    className="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
                    id="email"
                    onChange={(event) => updateField("email", event.target.value)}
                    placeholder="you@example.com"
                    required
                    type="email"
                    value={form.email}
                  />
                </div>

                <div>
                  <label className="mb-2 block text-[14px] font-medium text-[#6f6f6f]" htmlFor="role">
                    Role
                  </label>
                  <select
                    className="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 text-[14px] text-[#222] outline-none focus:border-[#11a63a] focus:bg-white"
                    id="role"
                    onChange={(event) => updateField("role", event.target.value)}
                    value={form.role}
                  >
                    {roles.map((role) => (
                      <option key={role} value={role}>
                        {role}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="mb-2 block text-[14px] font-medium text-[#6f6f6f]" htmlFor="password">
                    Password
                  </label>
                  <input
                    className="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
                    id="password"
                    onChange={(event) => updateField("password", event.target.value)}
                    placeholder="Enter your password"
                    required
                    type="password"
                    value={form.password}
                  />
                </div>

                <div className="pt-2">
                  <button
                    className="mx-auto block h-12 w-full rounded-xl bg-[#08b239] text-[15px] font-semibold text-white transition hover:bg-[#069d32] disabled:cursor-not-allowed disabled:opacity-60"
                    disabled={isPending}
                    type="submit"
                  >
                    {isPending ? "Signing up..." : "Sign up"}
                  </button>
                </div>

                <p className="text-center text-[14px] text-[#8a8a8a]">
                  Already have an account?
                  <Link className="ml-1 text-[#2563eb] hover:underline" href="/auth/sign-in">
                    Sign in
                  </Link>
                </p>
              </form>
            </div>
          </div>

          <div className="hidden lg:flex lg:border-l lg:border-gray-200">
            <div className="flex w-full items-center justify-center p-8">
              <div className="flex h-full w-full items-center justify-center bg-transparent">
                <div className="text-center text-gray-400">
                  <Image
                    alt="auth"
                    className="h-full w-full object-contain"
                    height={900}
                    src="/assets/images/auth.png"
                    width={900}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// founditfeold/src/app/components/auth/sign-up.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Eye, LUCIDE_ICONS, LucideAngularModule, LucideIconProvider } from 'lucide-angular';
import { LoginService } from '../../services/auth/Login/login.service';
import { Router, RouterLink } from '@angular/router';
import { SignUpService } from '../../services/auth/SignUp/sign-up.service';

@Component({
  selector: 'app-sign-up-component',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule, RouterLink],
  providers: [
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({ Eye }),
    },
  ],
  templateUrl: 'sign-up.component.html',
})
export class SignUpComponent {
  private signUpWithGoogle = inject(LoginService);
  private register = inject(SignUpService);
  private router = inject(Router);

  readonly icons = { Eye };

  fullName = '';
  email = '';
  password = '';
  confirmPassword = '';
  rememberMe = false;
  agreeTerms = false;

  isLoading = false;
  errorMessage = '';

  showPassword = false;
  showConfirmPassword = false;

  continueWithGoogle(): void {
    // Save email before redirecting to Google OAuth
    if (this.email) {
      localStorage.setItem('pending_email', this.email);
    }
    this.signUpWithGoogle.continueWithGoogle();
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword;
  }

  onSubmit(): void {
    this.errorMessage = '';

    const validationError = this.validateSignUpForm();
    if (validationError) {
      this.errorMessage = validationError;
      return;
    }

    this.isLoading = true;

    this.register
      .signUp({
        username: this.fullName.trim(),
        email: this.email.trim(),
        password: this.password,
      })
      .subscribe({
        next: (response) => {
          console.log('Signup success');
          localStorage.setItem('pending_email', this.email);
          this.router.navigateByUrl('/index', { replaceUrl: true });
          this.isLoading = false;
        },
        error: (error) => {
          console.error('Signup failed');
          this.errorMessage = this.readSignupError(error);
          this.isLoading = false;
        },
      });
  }

  get passwordsDoNotMatch(): boolean {
    return this.confirmPassword.length > 0 && this.password !== this.confirmPassword;
  }

  private validateSignUpForm(): string | null {
    if (!this.fullName.trim()) {
      return 'Full name is required.';
    }

    if (!this.email.trim()) {
      return 'Email is required.';
    }

    if (!this.isValidEmail(this.email)) {
      return 'Enter a valid email address.';
    }

    if (!this.password) {
      return 'Password is required.';
    }

    if (this.password.length < 8) {
      return 'Password must be at least 8 characters.';
    }

    if (!this.confirmPassword) {
      return 'Please re-enter your password.';
    }

    if (this.password !== this.confirmPassword) {
      return 'Password and confirm password do not match.';
    }

    if (!this.agreeTerms) {
      return 'Please agree to the Terms and Privacy policy.';
    }

    return null;
  }

  private isValidEmail(value: string): boolean {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());
  }

  private readSignupError(error: any): string {
    const body = error?.error;
    if (typeof body === 'string' && body.trim()) {
      return body;
    }

    if (body?.message) {
      return body.message;
    }

    return 'Signup failed. Please check your information and try again.';
  }
}

<div class="min-h-screen bg-[#f8f8f8] px-6 py-8 md:px-10 lg:px-16">
  <div class="mx-auto w-full">
    <!-- Logo -->
    <div class="flex justify-center mb-3">
      <div class="w-32 h-16 flex items-center">
        <img class="w-full h-full object-contain" src="/assets/images/logo.png" alt="FOUNDIT" />
      </div>   
    </div>

    <!-- Main content -->
    <div class="grid grid-cols-1 lg:grid-cols-[1.08fr_0.92fr]">
      <!-- Left -->
      <div class="flex items-start justify-center px-2 pt-8 md:px-6 lg:px-4 xl:px-8">
        <div class="w-full max-w-2xl">
          <h1 class="text-[42px] font-bold leading-tight text-[#1b1b1b]">
            Create an account
          </h1>
          <p class="mt-2 text-[18px] text-[#7b7b7b]">
            Sign Up With FoundIT
          </p>

          <!-- Social buttons -->
          <div class="mt-8 space-y-3">
            <button
              type="button"
              (click)="continueWithGoogle()"
              class="flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-[#e3e3e3] bg-white text-[14px] font-medium text-[#222] transition hover:bg-gray-50"
            >
              <img
                src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg"
                alt="Google"
                class="h-4 w-4"
              />
              <span>Continue with Google</span>
            </button>

          </div>

          <!-- Divider -->
          <div class="my-6 flex items-center gap-4">
            <div class="h-px flex-1 bg-[#e5e5e5]"></div>
            <span class="text-[13px] text-[#8a8a8a]">or use email</span>
            <div class="h-px flex-1 bg-[#e5e5e5]"></div>
          </div>

          <!-- Form -->
          <form (ngSubmit)="onSubmit()" class="space-y-4">
            <div
              *ngIf="errorMessage"
              class="rounded-xl border border-[#fecaca] bg-[#fef2f2] px-4 py-3 text-[14px] text-[#991b1b]"
            >
              {{ errorMessage }}
            </div>

            <!-- Full name -->
            <div>
              <label
                for="fullName"
                class="mb-2 block text-[14px] font-medium text-[#6f6f6f]"
              >
                Full name
              </label>
              <input
                id="fullName"
                name="fullName"
                type="text"
                [(ngModel)]="fullName"
                placeholder="Your name"
                class="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
              />
            </div>

            <!-- Email -->
            <div>
              <label
                for="email"
                class="mb-2 block text-[14px] font-medium text-[#6f6f6f]"
              >
                Email
              </label>
              <input
                id="email"
                name="email"
                type="email"
                [(ngModel)]="email"
                placeholder="you@example.com"
                class="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
              />
            </div>

            <!-- Password -->
            <div>
              <label
                for="password"
                class="mb-2 block text-[14px] font-medium text-[#6f6f6f]"
              >
                Password
              </label>

              <div class="relative">
                <input
                  id="password"
                  name="password"
                  [type]="showPassword ? 'text' : 'password'"
                  [(ngModel)]="password"
                  placeholder="Enter your password"
                  class="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 pr-12 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
                />

                <button
                  type="button"
                  (click)="togglePasswordVisibility()"
                  class="absolute right-4 top-1/2 -translate-y-1/2 text-[#9ca3af] hover:text-[#6b7280]"
                >
                  <lucide-angular
                    [img]="icons.Eye"
                    class="h-4 w-4"
                  ></lucide-angular>
                </button>
              </div>

              <p *ngIf="password && password.length < 8" class="mt-2 text-[13px] text-[#dc2626]">
                Password must be at least 8 characters.
              </p>
            </div>

            <!-- Confirm password -->
            <div>
              <label
                for="confirmPassword"
                class="mb-2 block text-[14px] font-medium text-[#6f6f6f]"
              >
                Confirm password
              </label>

              <div class="relative">
                <input
                  id="confirmPassword"
                  name="confirmPassword"
                  [type]="showConfirmPassword ? 'text' : 'password'"
                  [(ngModel)]="confirmPassword"
                  placeholder="Re-enter your password"
                  class="h-12 w-full rounded-xl border border-transparent bg-[#f1f1f3] px-4 pr-12 text-[14px] text-[#222] outline-none placeholder:text-[#9ca3af] focus:border-[#11a63a] focus:bg-white"
                />

                <button
                  type="button"
                  (click)="toggleConfirmPasswordVisibility()"
                  class="absolute right-4 top-1/2 -translate-y-1/2 text-[#9ca3af] hover:text-[#6b7280]"
                >
                  <lucide-angular
                    [img]="icons.Eye"
                    class="h-4 w-4"
                  ></lucide-angular>
                </button>
              </div>

              <p *ngIf="passwordsDoNotMatch" class="mt-2 text-[13px] text-[#dc2626]">
                Password and confirm password do not match.
              </p>
            </div>

            <!-- Checkboxes -->
            <div class="space-y-2 pt-1">
              <label class="flex items-center gap-2 text-[14px] text-[#333]">
                <input
                  type="checkbox"
                  name="rememberMe"
                  [(ngModel)]="rememberMe"
                  class="h-4 w-4 rounded border-gray-300 text-green-600 focus:ring-green-500"
                />
                <span>Remember me</span>
              </label>

              <label class="flex items-center gap-2 text-[14px] text-[#333]">
                <input
                  type="checkbox"
                  name="agreeTerms"
                  [(ngModel)]="agreeTerms"
                  class="h-4 w-4 rounded border-gray-300 text-green-600 focus:ring-green-500"
                />
                <span>
                  I agree to
                  <a href="#" class="text-[#2563eb] hover:underline">Terms</a>
                  &
                  <a href="#" class="text-[#2563eb] hover:underline">Privacy</a>
                </span>
              </label>
            </div>

            <!-- Submit -->
            <div class="pt-2">
              <button
                type="submit"
                [disabled]="isLoading"
                class="mx-auto block h-12 w-full rounded-xl bg-[#08b239] text-[15px] font-semibold text-white transition hover:bg-[#069d32] disabled:cursor-not-allowed disabled:opacity-60"
              >
                {{ isLoading ? 'Signing up...' : 'Sign up' }}
              </button>
            </div>

            <!-- Bottom link -->
            <p class="text-center text-[14px] text-[#8a8a8a]">
              Already have an account?<a routerLink="/auth/sign-in" class="ml-1 text-[#2563eb] hover:underline">
                Sign in
              </a>
            </p>
          </form>
        </div>
      </div>

      <!-- Right -->
      <div class="hidden lg:flex lg:border-l lg:border-gray-200">
        <div class="flex w-full items-center justify-center p-8">
          <div class="flex h-full w-full items-center justify-center rounded-none bg-transparent">
            <div class="text-center text-gray-400">
              <img class="w-full h-full object-contain" src="assets/images/auth.png" alt="auth.image">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
